import xml.etree.ElementTree as ET
import pathlib

black = "#292524"
orange = "#DB4B1A"
yellow = "#C6D431"
ybrown = "#7A6B1C"
silver = "#88898c"
white = "#FFFFEc"


patterns = {
    "appositus": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "fervidus": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "centralis": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "flavidus": {
    },
    "flavifrons": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "frigidus": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "griseocolis": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "huntii": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "impatiens": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "insularis": {
    },
    "kirbiellus": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "melanopygus": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "mixtus": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "morrisoni": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "nevadensis": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "occidentalis": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "rufocinctus": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "sitkensis": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "suckleyi": {
    },
    "sylvicola": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "vagans": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "vancouverensis": {
        "queen": [
            {
                "scutum_lr": black,
                "propodeum_m": black,
                "T2_al": orange,
                "T2_am": black,
                "T2_ar": orange,
                "T2_pl": orange,
                "T2_pm": orange,
                "T2_pr": orange,
                "T3_al": orange,
                "T3_am": orange,
                "T3_ar": orange,
                "T3_pl": orange,
                "T3_pm": orange,
                "T3_pr": orange,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pm": black,
                "T5_pr": black,
                "T5_pl": black,
            },
            {
                "face": silver,
                "vertex": silver,
                "pronotum": silver,
                "scutum_lr": black,
                "mesosoma_ar": white,
                "mesosoma_al": white,
                "mesosoma_pr": black,
                "mesosoma_pl": black,
                "propodeum_m": black,
                "propodeum_l": white,
                "propodeum_r": white,
                "T2_al": orange,
                "T2_am": black,
                "T2_ar": orange,
                "T2_pl": orange,
                "T2_pm": orange,
                "T2_pr": orange,
                "T3_al": orange,
                "T3_am": orange,
                "T3_ar": orange,
                "T3_pl": orange,
                "T3_pm": orange,
                "T3_pr": orange,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pr": black,
                "T5_pm": black,
                "T5_pl": black,
            },
            {
                "face": silver,
                "vertex": silver,
                "pronotum": silver,
                "scutum_lr": black,
                "mesosoma_ar": white,
                "mesosoma_al": white,
                "mesosoma_pr": black,
                "mesosoma_pl": black,
                "propodeum_m": black,
                "propodeum_l": white,
                "propodeum_r": white,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": orange,
                "T2_pm": black,
                "T2_pr": orange,
                "T3_al": orange,
                "T3_am": orange,
                "T3_ar": orange,
                "T3_pl": orange,
                "T3_pm": orange,
                "T3_pr": orange,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
            {
                "face": white,
                "vertex": white,
                "pronotum": silver,
                "scutum_lr": black,
                "mesosoma_ar": white,
                "mesosoma_al": white,
                "mesosoma_pr": black,
                "mesosoma_pl": black,
                "propodeum_m": black,
                "propodeum_l": white,
                "propodeum_r": white,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": orange,
                "T2_pm": black,
                "T2_pr": orange,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": orange,
                "T3_pm": orange,
                "T3_pr": orange,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
            {
                "face": white,
                "vertex": white,
                "pronotum": silver,
                "scutum_lr": black,
                "mesosoma_ar": white,
                "mesosoma_al": white,
                "mesosoma_pr": black,
                "mesosoma_pl": black,
                "propodeum_m": black,
                "propodeum_l": white,
                "propodeum_r": white,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
            {
                "pronotum": ybrown,
                "scutum_lr": black,
                "mesosoma_pr": black,
                "mesosoma_pl": black,
                "propodeum_m": black,
                "propodeum_l": yellow,
                "propodeum_r": yellow,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
        ],
        "worker": [
            {
                "scutum_lr": black,
                "propodeum_m": black,
                "T2_al": orange,
                "T2_am": black,
                "T2_ar": orange,
                "T2_pl": orange,
                "T2_pm": orange,
                "T2_pr": orange,
                "T3_al": orange,
                "T3_am": orange,
                "T3_ar": orange,
                "T3_pl": orange,
                "T3_pm": orange,
                "T3_pr": orange,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pm": black,
                "T5_pr": black,
                "T5_pl": black,
            },
            {
                "face": silver,
                "vertex": silver,
                "pronotum": silver,
                "scutum_lr": black,
                "mesosoma_ar": white,
                "mesosoma_al": white,
                "mesosoma_pr": black,
                "mesosoma_pl": black,
                "propodeum_m": black,
                "propodeum_l": white,
                "propodeum_r": white,
                "T2_al": orange,
                "T2_am": black,
                "T2_ar": orange,
                "T2_pl": orange,
                "T2_pm": orange,
                "T2_pr": orange,
                "T3_al": orange,
                "T3_am": orange,
                "T3_ar": orange,
                "T3_pl": orange,
                "T3_pm": orange,
                "T3_pr": orange,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pr": black,
                "T5_pm": black,
                "T5_pl": black,
            },
            {
                "face": silver,
                "vertex": silver,
                "pronotum": silver,
                "scutum_lr": black,
                "mesosoma_ar": white,
                "mesosoma_al": white,
                "mesosoma_pr": black,
                "mesosoma_pl": black,
                "propodeum_m": black,
                "propodeum_l": white,
                "propodeum_r": white,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": orange,
                "T2_pm": black,
                "T2_pr": orange,
                "T3_al": orange,
                "T3_am": black,
                "T3_ar": orange,
                "T3_pl": orange,
                "T3_pm": orange,
                "T3_pr": orange,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
            {
                "face": silver,
                "vertex": silver,
                "pronotum": silver,
                "scutum_lr": black,
                "mesosoma_ar": white,
                "mesosoma_al": white,
                "mesosoma_pr": black,
                "mesosoma_pl": black,
                "propodeum_m": black,
                "propodeum_l": yellow,
                "propodeum_r": yellow,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": orange,
                "T2_pm": black,
                "T2_pr": orange,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": orange,
                "T3_pm": black,
                "T3_pr": orange,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
            {
                "face": ybrown,
                "vertex": ybrown,
                "pronotum": ybrown,
                "scutum_lr": black,
                "mesosoma_ar": yellow,
                "mesosoma_al": yellow,
                "mesosoma_pr": black,
                "mesosoma_pl": black,
                "propodeum_m": black,
                "propodeum_l": yellow,
                "propodeum_r": yellow,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": orange,
                "T3_pm": black,
                "T3_pr": orange,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
            {
                "pronotum": ybrown,
                "scutum_lr": black,
                "mesosoma_pr": black,
                "mesosoma_pl": black,
                "propodeum_m": black,
                "propodeum_l": yellow,
                "propodeum_r": yellow,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
        ],
        "male": [
            {
                "scutum_lr": black,
                "propodeum_m": black,
                "T2_al": orange,
                "T2_ar": orange,
                "T2_pl": orange,
                "T2_pr": orange,
                "T3_al": orange,
                "T3_am": orange,
                "T3_ar": orange,
                "T3_pl": orange,
                "T3_pm": orange,
                "T3_pr": orange,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pm": black,
                "T6_ar": black,
                "T6_am": black,
                "T6_al": black,
                "T6_pr": black,
                "T6_pm": black,
                "T6_pl": black,
            },
            {
                "scutum_lr": black,
                "propodeum_m": black,
                "T2_al": black,
                "T2_ar": black,
                "T2_pl": orange,
                "T2_pm": black,
                "T2_pr": orange,
                "T3_al": orange,
                "T3_am": orange,
                "T3_ar": orange,
                "T3_pl": orange,
                "T3_pm": orange,
                "T3_pr": orange,
                "T5_al": ybrown,
                "T5_am": ybrown,
                "T5_ar": ybrown,
                "T6_ar": black,
                "T6_am": black,
                "T6_al": black,
                "T6_pr": black,
                "T6_pm": black,
                "T6_pl": black,
            },
            {
                "scutum_lr": ybrown,
                "scutum_m": ybrown,
                "propodeum_m": ybrown,
                "T2_al": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": ybrown,
                "T5_am": black,
                "T5_ar": ybrown,
                "T5_pm": black,
            },
            {
                "scutum_m": black,
                "scutum_lr": black,
                "propodeum_m": black,
                "T2_al": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pm": black,
                "T5_al": ybrown,
                "T5_am": black,
                "T5_ar": ybrown,
                "T5_pm": black,
                "T6_al": black,
                "T6_am": black,
                "T6_ar": black,
                "T6_pl": black,
                "T6_pm": black,
                "T6_pr": black,
            },
            {
                "scutum_lr": black,
                "scutum_m": black,
                "propodeum_m": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pm": black,
                "T6_al": black,
                "T6_am": black,
                "T6_ar": black,
                "T6_pl": black,
                "T6_pm": black,
                "T6_pr": black,
            },
        ],
    },
    "vandykei": {
        "queen": [
        ],
        "worker": [
        ],
        "male": [
        ],
    },
    "vosnesenskii": {
        "queen": [
            {
                "scutum_lr": black,
                "mesosoma_al": black,
                "mesosoma_pl": black,
                "mesosoma_ar": black,
                "mesosoma_pr": black,
                "propodeum_l": black,
                "propodeum_m": black,
                "propodeum_r": black,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            }
        ],
        "worker": [
            {
                "scutum_lr": black,
                "mesosoma_al": black,
                "mesosoma_pl": black,
                "mesosoma_ar": black,
                "mesosoma_pr": black,
                "propodeum_l": black,
                "propodeum_m": black,
                "propodeum_r": black,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            }
        ],
        "male": [
            {
                "scutum_lr": black,
                "mesosoma_al": ybrown,
                "mesosoma_pl": black,
                "mesosoma_ar": ybrown,
                "mesosoma_pr": black,
                "scutum_lr": ybrown,
                "scutum_m": ybrown,
                "propodeum_l": ybrown,
                "propodeum_m": ybrown,
                "propodeum_r": ybrown,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": ybrown,
                "T5_am": black,
                "T5_ar": ybrown,
                "T5_pl": yellow,
                "T5_pm": black,
                "T5_pr": yellow,
                "T6_al": black,
                "T6_am": black,
                "T6_ar": black,
                "T6_pl": black,
                "T6_pm": black,
                "T6_pr": black,
            },
            {
                "scutum_lr": black,
                "mesosoma_al": ybrown,
                "mesosoma_pl": black,
                "mesosoma_ar": ybrown,
                "mesosoma_pr": black,
                "scutum_lr": black,
                "scutum_m": black,
                "propodeum_r": black,
                "propodeum_m": black,
                "propodeum_l": black,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": ybrown,
                "T5_am": black,
                "T5_ar": ybrown,
                "T5_pl": yellow,
                "T5_pm": black,
                "T5_pr": yellow,
                "T6_al": black,
                "T6_am": black,
                "T6_ar": black,
                "T6_pl": black,
                "T6_pm": black,
                "T6_pr": black,
            },
        ]
    },
    "caliginosus": {
        "queen": [
            {
                "scutum_lr": black,
                "mesosoma_al": black,
                "mesosoma_pl": black,
                "mesosoma_ar": black,
                "mesosoma_pr": black,
                "propodeum_l": black,
                "propodeum_m": black,
                "propodeum_r": black,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
            {
                "scutum_lr": black,
                "mesosoma_al": black,
                "mesosoma_pl": black,
                "mesosoma_ar": black,
                "mesosoma_pr": black,
                "propodeum_r": black,
                "propodeum_m": black,
                "propodeum_l": black,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T4_ar": black,
                "T4_am": black,
                "T4_al": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
        ],
        "worker": [
            {
                "scutum_lr": black,
                "mesosoma_al": black,
                "mesosoma_pl": black,
                "mesosoma_ar": black,
                "mesosoma_pr": black,
                "propodeum_r": black,
                "propodeum_m": black,
                "propodeum_l": black,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
            {
                "scutum_lr": black,
                "mesosoma_al": black,
                "mesosoma_pl": black,
                "mesosoma_ar": black,
                "mesosoma_pr": black,
                "propodeum_l": black,
                "propodeum_m": black,
                "propodeum_r": black,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T4_ar": black,
                "T4_am": black,
                "T4_al": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
            },
        ],
        "male": [
            {
                "scutum_lr": black,
                "mesosoma_al": black,
                "mesosoma_pl": black,
                "mesosoma_ar": black,
                "mesosoma_pr": black,
                "propodeum_r": ybrown,
                "propodeum_m": ybrown,
                "propodeum_l": ybrown,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": yellow,
                "T5_pm": ybrown,
                "T5_pr": yellow,
                "T6_al": black,
                "T6_am": black,
                "T6_ar": black,
                "T6_pl": black,
                "T6_pm": black,
                "T6_pr": black,
            },
            {
                "scutum_lr": black,
                "mesosoma_al": black,
                "mesosoma_pl": black,
                "mesosoma_ar": black,
                "mesosoma_pr": black,
                "propodeum_r": black,
                "propodeum_m": black,
                "propodeum_l": black,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
                "T6_al": black,
                "T6_am": black,
                "T6_ar": black,
                "T6_pl": black,
                "T6_pm": black,
                "T6_pr": black,
            },
            {
                "scutum_lr": black,
                "mesosoma_al": black,
                "mesosoma_pl": black,
                "mesosoma_ar": black,
                "mesosoma_pr": black,
                "propodeum_r": black,
                "propodeum_m": black,
                "propodeum_l": black,
                "T1_l": black,
                "T1_m": black,
                "T1_r": black,
                "T2_al": black,
                "T2_am": black,
                "T2_ar": black,
                "T2_pl": black,
                "T2_pm": black,
                "T2_pr": black,
                "T3_al": black,
                "T3_am": black,
                "T3_ar": black,
                "T3_pl": black,
                "T3_pm": black,
                "T3_pr": black,
                "T4_ar": black,
                "T4_am": black,
                "T4_al": black,
                "T5_al": black,
                "T5_am": black,
                "T5_ar": black,
                "T5_pl": black,
                "T5_pm": black,
                "T5_pr": black,
                "T6_al": black,
                "T6_am": black,
                "T6_ar": black,
                "T6_pl": black,
                "T6_pm": black,
                "T6_pr": black,
            },
        ]
    },
}

def replace_colors(dom, colors):

    def rcr(node):
        path_id = node.attrib.get("id")
        if path_id is not None and path_id in colors:
            style = node.attrib.get("style")
            style_parts = style.split(";")
            fill_indeces = [i for i, x in enumerate(style_parts) if x.startswith("fill")]
            if fill_indeces:
                style_parts[fill_indeces[0]] = "fill:" + colors[path_id]
            style = ";".join(style_parts)
            node.attrib["style"] = style


        for child in node:
            rcr(child)

    rcr(dom.getroot())


for (species, castes) in patterns.items():
    for (caste, caste_patterns) in castes.items():
        for i, caste_pattern in enumerate(caste_patterns):
            if caste == "male":
                svg = ET.parse("bumblebee_male.svg")
            else:
                svg = ET.parse("bumblebee_female.svg")
            replace_colors(svg, caste_pattern)
            pathlib.Path("generated").mkdir(parents=True, exist_ok=True)
            svg.write(f"generated/{species}_{caste}{i}.svg")

